
import type * as BlocklyType from "blockly/core";

export function registerDroneBlocks(Blockly: typeof BlocklyType) {
	const define =
		(Blockly as any).common?.defineBlocksWithJsonArray ??
		(Blockly as any).defineBlocksWithJsonArray;
	
	define([
		{
			type: "drone_up",
			message0: "Bay lên %1 m",
			args0: [{ type: "field_number", name: "AMOUNT", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 230,
			tooltip: "Tăng độ cao drone theo mét",
		},
		{
			type: "drone_down",
			message0: "Đi xuống %1 m",
			args0: [{ type: "field_number", name: "AMOUNT", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 230,
			tooltip: "Giảm độ cao drone theo mét",
		},
		{
			type: "drone_left",
			message0: "Sang trái %1 m",
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: "Di chuyển drone sang trái theo trục X",
		},
		{
			type: "drone_right",
			message0: "Sang phải %1 m",
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: "Di chuyển drone sang phải theo trục X",
		},
		{
			type: "drone_forward",
			message0: "Tiến %1 m",
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: "Di chuyển drone về phía trước",
		},
		{
			type: "drone_back",
			message0: "Lùi %1 m",
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: "Di chuyển drone về phía sau",
		},
		{
			type: "drone_turn_right",
			message0: "Rẽ phải %1°",
			args0: [{ type: "field_angle", name: "DEG", value: 90 }],
			previousStatement: true,
			nextStatement: true,
			colour: 20,
			tooltip: "Quay drone sang phải theo độ",
		},
		{
			type: "drone_turn_left",
			message0: "Rẽ trái %1°",
			args0: [{ type: "field_angle", name: "DEG", value: 90 }],
			previousStatement: true,
			nextStatement: true,
			colour: 20,
			tooltip: "Quay drone sang trái theo độ",
		},
		{
			type: "drone_land",
			message0: "Hạ cánh",
			previousStatement: true,
			colour: 0,
			tooltip: "Hạ drone xuống đất",
		},
		{
			type: "drone_repeat",
			message0: "Lặp lại %1 lần",
			args0: [{ type: "field_number", name: "COUNT", value: 3, min: 1 }],
			previousStatement: true,
			nextStatement: true,
			message1: "Thực hiện %1",
			args1: [{ type: "input_statement", name: "DO" }],
			colour: 120,
			tooltip: "Lặp lại các lệnh bên trong N lần",
		},
		{
			type: "drone_if",
			message0: "Nếu %1",
			args0: [{ type: "input_value", name: "CONDITION" }],
			message1: "Thực hiện %1",
			args1: [{ type: "input_statement", name: "DO" }],
			previousStatement: true,
			nextStatement: true,
			colour: 60,
			tooltip: "Thực hiện nếu điều kiện đúng",
		},
		{
			type: "drone_if_else",
			message0: "Nếu %1",
			args0: [{ type: "input_value", name: "CONDITION" }],
			message1: "Thực hiện %1",
			args1: [{ type: "input_statement", name: "DO" }],
			message2: "Ngược lại %1",
			args2: [{ type: "input_statement", name: "ELSE" }],
			previousStatement: true,
			nextStatement: true,
			colour: 60,
			tooltip: "Thực hiện nếu/không nếu điều kiện",
		},
		{
			type: "drone_is_obstacle_ahead",
			message0: "Có chướng ngại vật phía trước?",
			output: "Boolean",
			colour: 300,
			tooltip: "Kiểm tra xem có vật cản phía trước drone",
		},
		{
			type: "drone_amount_value",
			message0: "%1",
			args0: [{ type: "field_number", name: "VAL", value: 1, min: 1, max: 10 }],
			output: "Number",
			colour: 230,
			tooltip: "Giá trị số để nối ngang",
		},
		{
			type: "drone_math_operation",
			message0: "%1 %2 %3",
			args0: [
				{ type: "input_value", name: "A" },
				{
					type: "field_dropdown",
					name: "OP",
					options: [
						["+", "ADD"],
						["-", "SUB"],
						["*", "MUL"],
						["/", "DIV"],
					],
				},
				{ type: "input_value", name: "B" },
			],
			output: "Number",
			colour: 230,
			tooltip: "Phép toán giữa hai số",
		},
		{
			type: "drone_play_sound",
			message0: "Phát âm thanh %1",
			args0: [
				{
					type: "field_dropdown",
					name: "SOUND",
					options: [
						["BEEP", "BEEP"],
						["ALARM", "ALARM"],
					],
				},
			],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: "Phát âm thanh cho drone",
		},
		{
			type: "drone_input_number",
			message0: "Nhập số %1",
			args0: [{ type: "field_number", name: "VAL", value: 0 }],
			output: "Number",
			colour: 230,
			tooltip: "Nhập một số từ người dùng",
		},
	]);
}

