import type * as BlocklyType from "blockly/core";
import { t } from "@/lib/translations-fakeeeee/sandbox";

export function registerDroneBlocks(Blockly: typeof BlocklyType) {
	const translations = t();
	const define =
		(Blockly as any).common?.defineBlocksWithJsonArray ??
		(Blockly as any).defineBlocksWithJsonArray;

	define([
		{
			type: "drone_take_off",
			message0: translations.blockly.blocks.takeOff.message,
			previousStatement: true,
			nextStatement: true,
			colour: 320,
			tooltip: translations.blockly.blocks.takeOff.tooltip,
		},
		{
			type: "drone_up",
			message0: translations.blockly.blocks.up.message,
			args0: [{ type: "field_number", name: "AMOUNT", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 230,
			tooltip: translations.blockly.blocks.up.tooltip,
		},
		{
			type: "drone_down",
			message0: translations.blockly.blocks.down.message,
			args0: [{ type: "field_number", name: "AMOUNT", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 230,
			tooltip: translations.blockly.blocks.down.tooltip,
		},
		{
			type: "drone_left",
			message0: translations.blockly.blocks.left.message,
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: translations.blockly.blocks.left.tooltip,
		},
		{
			type: "drone_right",
			message0: translations.blockly.blocks.right.message,
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: translations.blockly.blocks.right.tooltip,
		},
		{
			type: "drone_forward",
			message0: translations.blockly.blocks.forward.message,
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: translations.blockly.blocks.forward.tooltip,
		},
		{
			type: "drone_back",
			message0: translations.blockly.blocks.backward.message,
			args0: [{ type: "field_number", name: "DIST", value: 1, min: 1, max: 10, precision: 1 }],
			previousStatement: true,
			nextStatement: true,
			colour: 160,
			tooltip: translations.blockly.blocks.backward.tooltip,
		},
		{
			type: "drone_turn_right",
			message0: translations.blockly.blocks.turnRight.message,
			args0: [{ type: "field_number", name: "DEG", value: 90, min: 0, max: 360 }],
			previousStatement: true,
			nextStatement: true,
			colour: 20,
			tooltip: translations.blockly.blocks.turnRight.tooltip,
		},
		{
			type: "drone_turn_left",
			message0: translations.blockly.blocks.turnLeft.message,
			args0: [{ type: "field_number", name: "DEG", value: 90, min: 0, max: 360 }],
			previousStatement: true,
			nextStatement: true,
			colour: 20,
			tooltip: translations.blockly.blocks.turnLeft.tooltip,
		},
		{
			type: "drone_land",
			message0: translations.blockly.blocks.land.message,
			previousStatement: true,
			colour: 0,
			tooltip: translations.blockly.blocks.land.tooltip,
		},
		{
			type: "drone_repeat",
			message0: translations.blockly.blocks.repeat.message,
			args0: [{ type: "field_number", name: "COUNT", value: 3, min: 1 }],
			message1: "%1",
			args1: [{ type: "input_statement", name: "DO" }],
			previousStatement: true,
			nextStatement: true,
			colour: 120,
			tooltip: translations.blockly.blocks.repeat.tooltip,
		},
		{
			type: "drone_if",
			message0: translations.blockly.blocks.if.message,
			args0: [{ type: "input_value", name: "CONDITION", check: "Boolean" }],
			message1: "%1",
			args1: [{ type: "input_statement", name: "DO" }],
			previousStatement: true,
			nextStatement: true,
			colour: 210,
			tooltip: translations.blockly.blocks.if.tooltip,
		},
		{
			type: "drone_if_else",
			message0: translations.blockly.blocks.ifElse.message,
			args0: [{ type: "input_value", name: "CONDITION", check: "Boolean" }],
			message1: "%1",
			args1: [{ type: "input_statement", name: "DO" }],
			message2: "Ngược lại %1",
			args2: [{ type: "input_statement", name: "ELSE" }],
			previousStatement: true,
			nextStatement: true,
			colour: 210,
			tooltip: translations.blockly.blocks.ifElse.tooltip,
		},
		{
			type: "drone_is_obstacle_ahead",
			message0: translations.blockly.blocks.isObstacleAhead.message,
			output: "Boolean",
			colour: 210,
			tooltip: translations.blockly.blocks.isObstacleAhead.tooltip,
		},
		{
			type: "drone_amount_value",
			message0: "%1",
			args0: [{ type: "field_number", name: "VAL", value: 1, min: 1, max: 100 }],
			output: "Number",
			colour: 230,
			tooltip: translations.blockly.blocks.amountValue.tooltip,
		},
		{
			type: "drone_math_operation",
			message0: "%1 %2 %3",
			args0: [
				{ type: "input_value", name: "A", check: "Number" },
				{ type: "field_dropdown", name: "OP", options: [["+", "ADD"], ["-", "MINUS"], ["×", "MULTIPLY"], ["÷", "DIVIDE"]] },
				{ type: "input_value", name: "B", check: "Number" },
			],
			output: "Number",
			colour: 230,
			tooltip: translations.blockly.blocks.mathOperation.tooltip,
		},
		{
			type: "drone_play_sound",
			message0: translations.blockly.blocks.playSound.message,
			args0: [
				{ type: "field_dropdown", name: "SOUND", options: [["Beep", "beep"], ["Chime", "chime"], ["Buzzer", "buzzer"]] },
			],
			previousStatement: true,
			nextStatement: true,
			colour: 290,
			tooltip: translations.blockly.blocks.playSound.tooltip,
		},
		{
			type: "drone_input_number",
			message0: translations.blockly.blocks.inputNumber.message,
			args0: [{ type: "field_input", name: "PROMPT", text: "Nhập số" }],
			output: "Number",
			colour: 160,
			tooltip: translations.blockly.blocks.inputNumber.tooltip,
		},
	]);
}
