import { WORLD_SCALE, SIMULATION_CANVAS } from "./constants";


const CENTER_X = (SIMULATION_CANVAS.WIDTH * WORLD_SCALE.POSITION) / 2;
const CENTER_Z = (SIMULATION_CANVAS.HEIGHT * WORLD_SCALE.POSITION) / 5;
const DEFAULT_HEIGHT = Math.max(CENTER_X, CENTER_Z) * 0.2;
const DEFAULT_FAR = Math.max(SIMULATION_CANVAS.WIDTH, SIMULATION_CANVAS.HEIGHT) * WORLD_SCALE.POSITION * 4;

export const CAMERA_CONFIG = {
  INITIAL_POSITION: [0, DEFAULT_HEIGHT, CENTER_Z] as [number, number, number],
  FOV: 45,
  NEAR: 1,
  FAR: DEFAULT_FAR,
};

const MAP_RADIUS = Math.max(
  SIMULATION_CANVAS.WIDTH,
  SIMULATION_CANVAS.HEIGHT
) * WORLD_SCALE.POSITION / 2;

export const ORBIT_CONTROLS_CONFIG = {
  ENABLE_PAN: true,
  MAX_POLAR_ANGLE: Math.PI * 0.48,
  MIN_DISTANCE: Math.max(10, MAP_RADIUS * 0.15),
  MAX_DISTANCE: MAP_RADIUS * 2.8,
};

